"""initial schema

Revision ID: 077c40d3a148
Revises:
Create Date: 2026-09-05 16:12:05.331797

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "077c40d3a148"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
